### ISSUE TITLE
Mir compositor compatabilities missing

### ISSUE THREAD

**Issue by JamiKettunen** [vially/wayland-explorer#13]
Mir is a Wayland compositor library that provides a simple high-level API for building shells.
Upstream: https://github.com/MirServer/mir

![image](https://user-images.githubusercontent.com/47358222/187526087-4ad1fe62-3eec-4e02-8002-03dd75a8a9db.png)
Example: [wp_viewporter's compositor support](https://wayland.app/protocols/viewporter#compositor-support)

**Comment by JamiKettunen** [comment]
@vially Thoughts on this (and #14)? Mir is the underlying Wayland implementation used by the Ubuntu Touch UI called [Lomiri](https://lomiri.com) (formely known as Unity 8)

**Comment by vially** [comment]
I think both Mir and Weston would be nice additions to the compositor support table. According to the description from #9, I think adding support for Weston should just be a matter of running [wlprobe](https://github.com/PolyMeilex/wlprobe) inside a Weston session and using the resulting JSON file.

I'm adding the  `good first issue` label in case anyone wants to take a stab at it.

**Comment by JamiKettunen** [comment]
I assume results captured from an Arch Linux QEMU/KVM with `virtio-gpu` will do? In that case I can take a shot at capturing the file for both compositors :)
