### ISSUE TITLE
Ability to tell tested compositor version from support table

### ISSUE THREAD

**Issue by JamiKettunen** [vially/wayland-explorer#20]
I noticed there's no way to tell what version of the compositor the marketed features are available on, they're just updated "sometimes" as seen in e.g. https://github.com/vially/wayland-explorer/pull/17; I think at least a mouse hover on the text / logo showing the version of the compositor would be a very nice addition.

(from #18 originally)

**Comment by JamiKettunen** [comment]
Since `generationTimestamp` is already stored in the info as well perhaps that (alone even?) could be shown

**Comment by PolyMeilex** [comment]
I have added generation date to the UI some time ago: https://github.com/vially/wayland-explorer/pull/39

**Comment by JamiKettunen** [comment]
That's certainly better than nothing; maybe a version field later would be nice but this will do for now :)
