### ISSUE TITLE
Get rid of GitServiceProvider.GitHub for WaylandCore & WaylandProtocols

### ISSUE THREAD

**Issue by JamiKettunen** [vially/wayland-explorer#24]
They're irrelevant, upstream Wayland project has moved Freedesktop GitLab instance and the GitHub repos are no longer up-to-date (mirrored) nor archived.

See https://github.com/vially/wayland-explorer/pull/23#issuecomment-1384116644 and the PR in general for more details.

**Comment by vially** [comment]
Fixed in d1c24e6ef7cf35f7d23de443e3a9276ef5cccce7.
