### ISSUE TITLE
Add wl_drm protocol?

### ISSUE THREAD

**Issue by RPigott** [vially/wayland-explorer#3]
Hey there, nice site!

I notice you've included protocols from a variety of sources, but the widely supported wl_drm protocol from mesa is still missing. wl_drm is important for hardware accelerated clients, but intended for use in mesa, not by clients directly. You can find the xml definition here: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/egl/wayland/wayland-drm/wayland-drm.xml, if you want to include it.

**Comment by vially** [comment]
Sure, why not. I just pushed a commit to add it (bb552097b49772e49991f8e1ab0c7837c0df78f0): https://wayland.app/protocols/wayland-drm
