### ISSUE TITLE
Can we add hyprland?

### ISSUE THREAD

**Issue by iddm** [vially/wayland-explorer#42]
Can we add Hyprland to the "Compositor support" pages? Can I just create a PR to the page adding it and explaining why I think it is supported?

**Comment by vially** [comment]
I would expect the support of Hyprland to be pretty similar to sway considering they're both based on wlroots. But adding it to the support table definitely makes sense and it would be a nice addition.

**Comment by vaxerski** [comment]
> I would expect the support of Hyprland to be pretty similar to sway considering they're both based on wlroots.

Far from that, actually. Examples? 

 - fractional-scale was supported on hyprland way before sway
 - tearing is already supported in hyprland, sway doesnt do so
 - we have our own internal protocols as well (plumbing though, shouldn't be used by clients, but mostly xdph <-> hl) @ https://github.com/hyprwm/hyprland-protocols
 - supported versions differ, as an example, xdg-shell: hl - 5, sway - 2
 
> Or, perhaps we could rename the current entry from "Sway" to wlroots?

Bad idea, wlroots-based compositors differ a lot by the supported protocols and versions. Compare for example vivarium or dwl to hyprland or sway.

**Comment by vaxerski** [comment]
if anyone needs info regarding supported protocols in hyprland and their versions, feel free to hmu on discord / matrix
