### ISSUE TITLE
virtual_keyboard protocol doesn't match the actual one used by compositors/clients

### ISSUE THREAD

**Issue by kchibisov** [vially/wayland-explorer#45]
See https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/virtual-keyboard-unstable-v1.xml?ref_type=heads

It doesn't have `destroy` for `manager` and never had one.

**Comment by vially** [comment]
Thanks for flagging this. I've updated the protocol to match the current implementations (https://github.com/vially/wayland-explorer/commit/f8fb6ec96c06cb82ad2a551d669b3f5f1a2e0cf1) but I think the version with the `manager.destroy` request might be the latest one ([source](https://lists.freedesktop.org/archives/wayland-devel/2019-September/040882.html)).

Although that doesn't really mean much if the compositors and clients don't implement it yet.
