### ISSUE TITLE
Improve Deprecations and Mark `wl_pointer::axis_discrete` as Deprecated

### ISSUE THREAD

**Issue by bbb651** [vially/wayland-explorer#57]
I noticed [`wl_pointer::axis_discrete`](https://wayland.app/protocols/wayland#wl_pointer:event:axis_discrete) isn't marked as deprecated. As far as I can tell, all other [depreciations](https://github.com/vially/wayland-explorer/blob/main/src/data/protocol-registry.ts) are on objects or protocols, not on a method/event (and even arguments like in [`wl_output::mode`](https://wayland.app/protocols/wayland#wl_output:event:mode) can be deprecated although they are harder to mark because you need the context provided in the description, but it would be nice to mark them too), it would be nice to support these as well.

**Comment by bbb651** [comment]
I feel like it would be better to have the protocols themselves contain deprecations, it'll be more maintainable and help other documentation sites/reading the protocols in text, do you know if there's an upstream issue/proposal for it?

**Comment by emersion** [comment]
See https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/329

**Comment by PolyMeilex** [comment]
Yeah, the depreciations should just be in the XML, the current solution that I did is only meant to be a stopgap for now, and that's also why it's so bare bones.
