### ISSUE TITLE
link to original specifications

### ISSUE THREAD

**Issue by lolbinarycat** [vially/wayland-explorer#71]
the github breaks cross-site submodules, and it took me quite a lot of digging to find the actual wayland-protocols repo.

**Comment by PolyMeilex** [comment]
You can just click on the file name in the breadcrumb, like so and it will open the source:
![image](https://github.com/vially/wayland-explorer/assets/20758186/be94c00b-ab49-41ba-9958-6efc1ef44ad7)

**Comment by lolbinarycat** [comment]
that element seems to not be present on mobile firefox.
